name: Backup Repository

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create backup branch
        id: create_branch
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          BRANCH_NAME="backup-$TIMESTAMP"
          echo "Creating branch $BRANCH_NAME"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Add backup remote
        run: |
          echo "Adding remote backup repository"
          git remote add backup https://${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}@github.com/kn-oz/backuprepo.git

      - name: Push to backup repository
        run: |
          echo "Pushing to remote repository"
          git push backup ${{ env.BRANCH_NAME }}
