name: Backup Repository

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all branches

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create backup branch
        id: create_branch
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          BRANCH_NAME="backup-$TIMESTAMP"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Add backup remote
        run: git remote add backup https://YOUR_PERSONAL_ACCESS_TOKEN@github.com/kn-oz/BACKUPREPO.git
        env:
          YOUR_PERSONAL_ACCESS_TOKEN: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}

      - name: Push to backup repository
        run: git push backup ${{ env.BRANCH_NAME }}
