# File: .github/workflows/repo-sync.yml

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "kn-oz/JDBCWORKS" # Your source repository
          source_branch: "main" # Replace with the branch you want to sync from
          destination_repo: "kn-oz/BACKUPREPO" # Your destination repository
          destination_branch: "main" # Replace with the branch you want to sync to in the destination repository
          github_token: ${{ secrets.PAT }}


