name: Backup Repository

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash --login -o pipefail

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create backup branch
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          BRANCH_NAME="backup-$TIMESTAMP"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Backup on $TIMESTAMP"
          git remote add backup https://github.com/kn-oz/BACKUPREPO.git
          git push -u backup $BRANCH_NAME
        env:
          PAT: ${{ secrets.PAT }}

