name: Backup Files

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: your-username/source-repo
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Sync files to backup repository
      run: |
        git clone https://github.com/kn-oz/BACKUPREPO.git
        cp -r ./source-folder/* ./BACKUPREPO/
        cd BACKUPREPO
        git add .
        git commit -m "Automated backup"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

